### ISSUE TITLE
24 format input template

### ISSUE THREAD

**Issue by Robinson3034** [owsolutions/amazing-time-picker#40]
Can you give 24 format time selection instead of select AM and PM

**Comment by torabian** [comment]
Can you describe more that how we have to do it and what's suits you best ?

**Comment by Simbaclaws** [comment]
Check out my reference on [#42](https://github.com/owsolutions/amazing-time-picker/issues/42). 
I think this would be the ideal way to add such functionality IMHO.
Would be rather user friendly to have another inner circle that counts up to 24 or 0 from 13

**Comment by Robinson3034** [comment]
Check out this link  http://weareoutman.github.io/clockpicker/  for 24 hours format

**Comment by torabian** [comment]
I would not recommend this type of clock because:
1- As a design perspective, there are too many elements than usual, and it's not a familiar for user to choice type like this.
2- We will lose our mousedown feature that helps user to select type by twisting the mouse, not only clicking on the actual numbers.

If you still thinking that this is a good solution or necessary for you, feel free to reopen this issue and provide a workaround on this.

**Comment by etwillbefine** [comment]
Just from my "german perspective". We cannot offer a datepicker to our customers with AM/PM. Especially older people will be lost. At this point I want to quote from wikipedia:
`The 24-hour clock is the convention of time keeping in which the day runs from midnight to midnight and is divided into 24 hours, indicated by the hours passed since midnight, from 0 to 23. This system is the most commonly used time notation in the world today,[1] and is used by international standard ISO 8601.` https://en.wikipedia.org/wiki/24-hour_clock#cite_note-cldr-1

I really dont think that this feature doesnt need to be supported because of "technical or design issues"
